# Sublime

## Sublime 配置Python3
打开 Tools > Build System > New Build System
输入以下内容：
```
"encoding": "utf-8",  
"working_dir": "$file_path",  
"shell_cmd": "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe -u \"$file\"",  
"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",  
"selector": "source.python"  
 ```
然后 Ctrl + S 直接保存为想要命名的编译名称（如：python352）：
然后重启 Sublime text 3 选择 python 352 即可：

### input设置
由于Sublime text 3 没有默认提供python的input()的输入窗口，所以当你想要键入一些数据的时候，根本无进行操作的，所以需要安装一个叫做sublimeREPL 的插件。

打开package control 选项 输入Install Package，回车，在新出现的输入框里输入SublimeREPL 搜索到以后进行安装。

然后来测试一下效果：

建立一个带有input()功能的测试python脚本，然后  tools> SublimeREPL > python > python - run current file ,在新打开的页面输入 19，即打印了相应的判断结果：

然后就会有一个问题，就是每次需要类似操作的时候，均需要  tools >  SublimeREPL > python > python - run current file的步骤，十分的麻烦，所以就进行一个快捷键的设置：

### 设置快捷键
打开 preferences>key bindings :
输入以下信息后保存即可：
复制代码
{  
  
"keys":["f5"],  
"caption": "SublimeREPL: Python - RUN current file",  
"command": "run_existing_window_command", "args": {"id": "repl_python_run",  
"file": "config/Python/Main.sublime-menu"}  
  
}  
复制代码
 
至此，快捷键就设置完成了，其实此时的f5 就和python 自带的 ide 的 f5 功能一样了，相当于执行程序了。

